# This file is auto-generated by save-gdb-breakpoints
# To load this file, run `source <path-to-this-file>` in GDB

# break elf_loader.c:236
# break process.c:90
# break process.c:140
# break process.c:182
break process.c:278
