# This file is auto-generated by save-gdb-breakpoints
# To load this file, run `source <path-to-this-file>` in GDB

# break elf_loader.c:236
# break process.c:91
# break process.c:142
# break process.c:184
# break fork.c:120
break execve.c:37
